frappe/crm

frontend/src/components/LayoutHeader.vue
After login header is not visible after refresh it becomes visible
Before:
After:
=> fix: after login header is not rendered

frontend/src/App.vue, frontend/src/components/Activities.vue, frontend/src/components/CommunicationArea.vue, frontend/src/components/NewDeal.vue, frontend/src/components/NewLead.vue, frontend/src/components/UserAvatar.vue, frontend/src/composables/filter.js, frontend/src/main.js, frontend/src/pages/CallLog.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Login.vue, frontend/src/pages/Notes.vue, frontend/src/router.js, frontend/src/stores/session.js
=> Revert "refactor: made session, getUser, users globalProperty"

crm/api/doc.py, crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_lead/api.py, crm/fcrm/doctype/crm_lead/crm_lead.json, crm/fcrm/doctype/crm_lead/crm_lead.py, crm/fcrm/doctype/crm_organization/crm_organization.py, frontend/src/components/SectionFields.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
=> feat: Minor features

crm/api/doc.py, crm/fcrm/doctype/crm_task/crm_task.py, frontend/src/components/Filter.vue, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/Modals/TaskModal.vue, frontend/src/pages/Tasks.vue, frontend/src/router.js
=> feat: Tasks ListView

crm/overrides/email_template.py, frontend/src/components/Modals/EmailTemplateModal.vue, frontend/src/components/Modals/EmailTemplateSelectorModal.vue, frontend/src/pages/EmailTemplates.vue
fixes: https://github.com/frappe/crm/issues/198
=> fix: show use_html & response_html in Email Template Modal

crm/api/contact.py, crm/api/doc.py, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_organization/crm_organization.json, crm/fcrm/doctype/crm_organization/crm_organization.py, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Organization.vue, frontend/src/pages/Organizations.vue, frontend/src/utils/index.js
fixes: https://github.com/frappe/crm/issues/223
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>
=> fix: added/render currency for deal & organization amount field

frontend/package.json, frontend/src/components/Activities.vue, frontend/src/components/EmailContent.vue, frontend/src/components/EmailEditor.vue, yarn.lock
=> feat: Email Reply Collapser

crm/hooks.py
Depended on https://github.com/frappe/frappe/pull/27292/
Updated hooks.py to include crm app in apps page
=> fix: include crm in apps page

frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/stores/statuses.js, frontend/src/utils/index.js
Add a `Form Script` to add custom statuses based on different conditions
E.g. if you need different set of statuses to display in the dropdown based on different condition you can achieve this now by conditionally setting statuses based on your business requirements
<kbd>
</kbd>
Product Statuses
<kbd>
</kbd>
Service Statuses
<kbd>
</kbd>
=> feat: show custom statuses in Lead/Deal page

crm/fcrm/doctype/crm_form_script/crm_form_script.js, crm/fcrm/doctype/crm_form_script/crm_form_script.json, crm/fcrm/doctype/crm_form_script/crm_form_script.py
You can add standard form script which will be non editable but you can enable or disable it
<kbd>
</kbd>
=> feat: allow adding standard form script

crm/api/demo.py, crm/hooks.py, crm/overrides/user.py
Api to login using demo username & password mentioned in site config
E.g
`site_config.json`
```
"demo_username": "john.doe@demo.com"
"demo_password": "password@123",
```
Open this link to login into your system with demo credentials
```
https://<sitename>/api/method/crm.api.demo.login
```
> NOTE: Demo user cannot reset password, but make sure to create a user on your site before using above link and restrict user.
=> fix: api's for live demo site

frontend/src/composables/useActiveTabManager.js, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
- Implemented functionality to store and retrieve the last visited tab index in localStorage.
- The application now defaults to the last visited tab after a page refresh, rather than always returning to the Activity tab.
- This ensures that users remain on the same tab they were on before refreshing the page, improving user experience.
[Screencast from 09-08-24 12:45:17 PM IST.WEBM](https://github.com/user-attachments/assets/412d73fa-1660-4994-99ff-dbd8e1acf966)
Closes #192
=> feat: Preserve last visited tab

crm/fcrm/doctype/erpnext_crm_settings/erpnext_crm_settings.py
There is no doctype name of Frappe CRM Deal
=> fix: quotation to option

crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py
- Added a null check (`and field.options`) in the condition to handle cases where options are empty or undefined for "Select" type fields.
When I added a custom field of type Select without options, then code attempted to split `field.options` without checking if it existed, which could result in errors when `field.options` is `None` or an empty string which resulted in error and not loading all the fields after that field. By adding this check, we ensure that the code only attempts to split the options when `field.options` has a value.
```python
if field.fieldtype == "Select" and field.options:
field.options = field.options.split("\n")
Try creating a select field without options and then add it in sections field layout. then if you try to edit the layout it will cause the error and some …
```
=> Fix: Add null check for Select field options in fields_layout

crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py
Custom fields with link filters defined were not reflecting on the CRM portal
the root cause is that the get_fields_layout API is not responding with the filters.
With this small change, it is working as expected
=> fix: Link field filters

crm/fcrm/doctype/crm_call_log/test_crm_call_log.py, crm/fcrm/doctype/crm_communication_status/test_crm_communication_status.py, crm/fcrm/doctype/crm_deal/test_crm_deal.py, crm/fcrm/doctype/crm_deal_status/test_crm_deal_status.py, crm/fcrm/doctype/crm_fields_layout/test_crm_fields_layout.py, crm/fcrm/doctype/crm_form_script/test_crm_form_script.py, crm/fcrm/doctype/crm_holiday_list/test_crm_holiday_list.py, crm/fcrm/doctype/crm_industry/test_crm_industry.py, crm/fcrm/doctype/crm_invitation/test_crm_invitation.py, crm/fcrm/doctype/crm_lead/test_crm_lead.py, crm/fcrm/doctype/crm_lead_source/test_crm_lead_source.py, crm/fcrm/doctype/crm_lead_status/test_crm_lead_status.py, crm/fcrm/doctype/crm_notification/test_crm_notification.py, crm/fcrm/doctype/crm_organization/test_crm_organization.py, crm/fcrm/doctype/crm_service_level_agreement/test_crm_service_level_agreement.py, crm/fcrm/doctype/crm_service_level_priority/test_crm_service_level_priority.py, crm/fcrm/doctype/crm_task/test_crm_task.py, crm/fcrm/doctype/crm_territory/test_crm_territory.py, crm/fcrm/doctype/crm_view_settings/test_crm_view_settings.py, crm/fcrm/doctype/erpnext_crm_settings/test_erpnext_crm_settings.py, crm/fcrm/doctype/fcrm_note/test_fcrm_note.py, crm/fcrm/doctype/twilio_agents/test_twilio_agents.py, crm/fcrm/doctype/twilio_settings/test_twilio_settings.py
Fixed failing unit test with below error
```
frappe.testing.discovery.TestRunnerError: Failed to discover tests for ['crm']: function() argument 'code' must be code, not str
```
**Cause:**
PR Link: https://github.com/frappe/frappe/pull/28044
=> test: fixed failing unit test

crm/fcrm/doctype/fcrm_settings/fcrm_settings.js, crm/fcrm/doctype/fcrm_settings/fcrm_settings.json, crm/fcrm/doctype/fcrm_settings/fcrm_settings.py, crm/fcrm/doctype/fcrm_settings/test_fcrm_settings.py, crm/install.py
=> fix: Restore defaults

crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_lead/crm_lead.py
This PR is a fix to this issue #417
Previously the share permissions were revoked from the assignees each time the lead and deal get evaluated.
this PR checks if the owner of doc has changed and then revokes the perms.
Code Changed
```py
if not self.is_new():
curr_owner = frappe.db.get_value(self.doctype,self.name,"lead_owner")
if self.lead_owner and self.lead_owner != curr_owner:
self.share_with_agent(self.lead_owner)
self.assign_agent(self.lead_owner)
```
=> Fix: assigning to new owner and revoking old assignees permissions upon lead_owner change

README.md, docker/docker-compose.yml, docker/init.sh
The quickest way to set up Frappe CRM and take it for a test ride.
Frappe framework is multi-tenant and supports multiple apps by default. This docker compose is just a standalone version with Frappe CRM pre-installed. Just put it behind your desired reverse-proxy if needed, and you're good to go.  
If you wish to use multiple Frappe apps or need multi-tenancy. Take a look at our production ready self-hosted workflow, or join us on Frappe Cloud to get first party support and hassle-free hosting.
**Step 1**: Setup folder and download the required files
mkdir frappe-crm
cd frappe-crm
**Step 2**: Download the required files
Docker Compose File:
wget -O docker-compose.yml https://raw.githubusercontent.com/frappe/crm/develop/docker/docker-compose.yml
Frappe CRM bench setup script
wget -O …
=> fix: docker install steps in Readme

crm/integrations/twilio/api.py
Follow up to https://github.com/frappe/frappe/pull/28093 so I can drop the pytz dependency
=> refactor: drop pytz usage

crm/fcrm/doctype/crm_deal/crm_deal.json
Renamed `Amount` to `Annual Revenue` to keep it consistent over Lead & Deal.
=> chore: renamed Amount to Annual Revenue

crm/fcrm/doctype/crm_dropdown_item/crm_dropdown_item.json, crm/fcrm/doctype/crm_dropdown_item/crm_dropdown_item.py, crm/fcrm/doctype/fcrm_settings/fcrm_settings.json, crm/fcrm/doctype/fcrm_settings/fcrm_settings.py, crm/hooks.py, crm/install.py, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/Mobile/MobileSidebar.vue, frontend/src/components/UserDropdown.vue
**Add / Edit / Hide dropdown items**
**Dropdown Items in FCRM Settings**
=> feat: Custom dropdown items

crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, frontend/src/components/Controls/Grid.vue, frontend/src/components/Controls/GridFieldsEditorModal.vue, frontend/src/components/Controls/GridRowModal.vue, frontend/src/components/Controls/ImageUploader.vue, frontend/src/components/FieldLayout.vue, frontend/src/components/Settings/GeneralSettings.vue, frontend/src/components/Settings/InviteMemberPage.vue, frontend/src/components/Settings/Settings.vue, frontend/src/components/Settings/SettingsPage.vue, frontend/src/components/UserDropdown.vue, frontend/src/stores/meta.js, frontend/src/stores/settings.js
It includes
1. Branding
2. Favicon
3. Dropdown Settings
=> feat: Moved CRM Settings to Portal

frontend/src/components/Activities/EmailContent.vue, frontend/src/components/CustomActions.vue, frontend/src/components/FilesUploader/FilesUploaderArea.vue, frontend/src/components/Kanban/KanbanView.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Leads.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue, frontend/src/stores/statuses.js, frontend/src/utils/index.js
fixes: https://github.com/frappe/crm/issues/501
fixes: https://github.com/frappe/crm/issues/503
=> refactor: custom actions not loading on second visit

frontend/package.json, frontend/src/components/Activities/DataFields.vue, frontend/src/components/FieldLayout.vue, frontend/src/components/Modals/AddressModal.vue, frontend/src/components/Modals/ContactModal.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/components/Section.vue, frontend/src/components/SidePanelLayout.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue, yarn.lock
dependent on: https://github.com/frappe/frappe-ui/pull/251
=> refactor: Tabs layout (frappe-ui)

crm/fcrm/doctype/crm_notification/crm_notification.py
This PR fixes the issue #594  where every user received a WebSocket event for all CRM notifications, causing unnecessary API reloads. Now, the event is emitted only for the intended recipient, reducing server load and improving efficiency.
Updated `frappe.publish_realtime("crm_notification")` to send the event only to the relevant user.
<br>
```py
frappe.publish_realtime("crm_notification")
```
<br>
```py
frappe.publish_realtime("crm_notification", user=self.recipient)
```
=> Fix unnecessary notification API reloads for all users

frontend/src/components/Modals/DealModal.vue
This PR fixes an issue #598  where previously selected contact details remain in the form data even after switching to a new contact. Now, all contact-related fields are cleared when toggling the "Choose Existing Contact" option.
✅ Clears all contact-related fields when chooseExistingContact is checked
✅ Ensures contact field is null when chooseExistingContact is unchecked
✅ Prevents unnecessary data from being sent to the API
```js
...
function createDeal() {
if (deal.website && !deal.website.startsWith('http')) {
deal.website = 'https://' + deal.website
}
createResource({
url: 'crm.fcrm.doctype.crm_deal.crm_deal.create_deal',
params: { args: deal },
...
```
```js
...
function createDeal() {
if (deal.website && !deal.website.startsWith('http')) {
deal.website = 'https://' + deal.website …
```
=> Clear contact details when switching from existing to new contact

frontend/src/components/ViewControls.vue
This PR fixes a critical issue #628 where `crm.api.doc.get_data` was being called infinitely when pagination or refresh was clicked while a previous request was still pending.  
The `updatePageLength` function was not checking if a request was already in progress, leading to uncontrolled API calls.  
Added the following check at the beginning of `updatePageLength`:  
```javascript
if (list.value.loading) return
```
This prevents new API calls if a request is already in progress, effectively solving the issue.
I don't know if this is the right solution, but this seems to have fixed the problem for now.
=> Fix Infinite API Calls in updatePageLength

frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue
In leads and deals list view, remove logic to set lead owner as default "Assigned to" when it is cleared
=> fix: default "assigned to" in deals and leads list view

frontend/components.d.ts, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue
Removes logic to set lead owner as default "Assigned to" when it is cleared
=> fix: default assigned to in leads list view

frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue
Fixed export logic where while exporting data when user selects rows from list view only those rows are exported instead of all
Fixes #673
=> fix: export logic

crm/api/whatsapp.py
The last name on CRM Leads can be empty. In cases where it is, an error occurs: can only concatenate str (not "NoneType") to str. This prevents retrieving messages until a last name is added.
=> fix(WhatsApp): prevent TypeError when concatenating first and last name

crm/install.py
```python
lost_reasons = [
{
"reason": "Pricing",
"description": "The prospect found the pricing to be too high or not competitive.",
},
{"reason": "Competition", "description": "The prospect chose a competitor's product or service."},
{
"reason": "Budget Constraints",
"description": "The prospect did not have the budget to proceed with the purchase.",
},
{
"reason": "Missing Features",
"description": "The prospect felt that the product or service was missing key features they needed.",
},
{
"reason": "Long Sales Cycle",
"description": "The sales process took too long, leading to loss of interest.",
},
{
"reason": "No Decision-Maker",
"description": "The prospect was not the decision-maker and could not proceed.",
},
{"reason": "Unresponsive Prospect", "description": "The prospect did not …
```
=> fix: add default lost reason on install

crm/api/dashboard.py, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_deal_status/crm_deal_status.json, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.json, crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py, crm/fcrm/doctype/fcrm_settings/fcrm_settings.json, crm/fcrm/doctype/fcrm_settings/fcrm_settings.py, crm/install.py, crm/patches.txt, crm/patches/v1_0/update_deal_status_type.py, frontend/src/pages/Dashboard.vue, frontend/src/pages/Deal.vue, frontend/src/pages/MobileDeal.vue, frontend/src/stores/statuses.js
Based on `type` we can handle `Won` or `Lost` deals for forecasting, lost reason trigger features and to get accurate data in dashboard charts & number card
<kbd><img width="1164" height="413" alt="Screenshot 2025-07-13 at 3 11 51 PM" src="https://github.com/user-attachments/assets/ee1390d2-7a42-4b28-9317-3eed56c059e5" /></kbd>
<kbd><img width="442" height="173" alt="Screenshot 2025-07-13 at 3 12 59 PM" src="https://github.com/user-attachments/assets/65385afc-daf3-468e-853c-1d108ca1f526" /><kbd>
1. "Total deals" is now "Ongoing deals" and added average deal value number card for ongoing deals
2. "Won deals" is based on `closed_date` field and added average deal value number card for won deals
3. Separated "Average time to close" into "Average time to close a lead" & "Average time to close …
=> refactor: Dashboard & categories deal status

frontend/src/components/Modals/OrganizationModal.vue
In this case user can add the details and save the form again instead of refreshing and then trying again for fresh.
=> fix(Org Modal): Setting loading false in case of Validation Error

crm/fcrm/doctype/crm_deal/crm_deal.json
Fix primary email, mobile & phone number not visible in deals data tab and new deal modal by removing "read only" flag for them
=> fix: remove "read only" flag for primary email, mobile & phone no

crm/api/whatsapp.py
made changes so that:
1. whatsapp message is created (app: frappe_whatsapp) even if no phone number match is found in CRM Deal & CRM Lead.
2. Also assigns reference doctype and name for Outgoing whatsappe messages which are not sent via CRM app.
3. added a "if doctype and" check to make sure notify_agent does not fail whatsapp message creation if whatsapp message is being created as per step 1.
4. 
Also solves this: https://github.com/shridarpatil/whatsapp_chat/issues/4
=> Added support for outgoing whatsapp messages from other apps
