frappe/crm

crm/fcrm/doctype/twilio_settings/twilio_settings.json, crm/fcrm/doctype/twilio_settings/twilio_settings.py, crm/twilio/api.py, frontend/src/components/CallUI.vue
Auto generate api_key, api_secret etc on update of twilio_settings
=> fix: generate api_key, api_secret on update of twilio settings

frontend/src/components/AppHeader.vue, frontend/src/components/CallUI.vue, frontend/src/components/Icons/IndicatorIcon.vue, frontend/src/components/LayoutHeader.vue, frontend/src/components/ListView.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue
=> fix: Listview re-design

crm/fcrm/workspace/frappe_crm/frappe_crm.json, frontend/src/pages/Deal.vue
=> fix: Added CRM Workspace

crm/api/doc.py, crm/fcrm/doctype/crm_call_log/crm_call_log.py, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_lead/crm_lead.py, crm/fcrm/doctype/crm_list_view_settings/crm_list_view_settings.py, crm/fcrm/doctype/crm_organization/crm_organization.py, crm/hooks.py, crm/overrides/contact.py, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ViewSettings.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue
=> fix: Apply Filter, Sort & List View Settings on Contact, Organization & Call Log List

frontend/src/components/Activities.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Notes.vue, frontend/src/pages/Organization.vue, frontend/src/pages/Organizations.vue
=> fix: Added empty states

crm/api/doc.py, crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_lead/api.py, crm/fcrm/doctype/crm_lead/crm_lead.py, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/Modals/AssignmentModal.vue, frontend/src/components/MultipleAvatar.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Leads.vue
https://github.com/frappe/crm/assets/30859809/4a7363a6-7c65-4a4a-b646-e2b73bf50101
=> feat: Multiple assignment in Lead/Deal

crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_form_script/crm_form_script.js, crm/fcrm/doctype/crm_form_script/crm_form_script.json, crm/fcrm/doctype/crm_form_script/crm_form_script.py, crm/fcrm/doctype/crm_form_script/test_crm_form_script.py, crm/fcrm/doctype/crm_lead/api.py, frontend/src/components/CustomActions.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/utils/index.js
Custom Actions
Custom Grouped Actions
=> feat: Custom Actions on Lead/Deal Page

crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_lead/crm_lead.json, crm/fcrm/doctype/crm_organization/crm_organization.json, crm/fcrm/doctype/crm_territory/crm_territory.js, crm/fcrm/doctype/crm_territory/crm_territory.json, crm/fcrm/doctype/crm_territory/crm_territory.py, crm/fcrm/doctype/crm_territory/test_crm_territory.py, crm/fcrm/workspace/frappe_crm/frappe_crm.json, frontend/src/components/Icons/TerritoryIcon.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Organization.vue
Added territory field in Lead/Deal & Organization
=> fix: create territory doctype and added in lead/deal/organization

crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_lead/crm_lead.json, crm/fcrm/doctype/crm_lead/crm_lead.py, crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.json, crm/fcrm/doctype/crm_status_change_log/crm_status_change_log.py
When status changes in Lead or Deal log from, to, from_date, to_date & duration
=> feat: Add status change log in Lead/Deal

crm/api/doc.py, frontend/package.json, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, yarn.lock
https://github.com/frappe/crm/assets/30859809/7182bca3-8dff-49b9-8fdf-8a971f904168
depends on: https://github.com/frappe/frappe-ui/pull/121
=> feat: List View Footer to control pagination

crm/api/session.py, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/twilio/api.py, crm/twilio/twilio_handler.py, crm/twilio/utils.py, frontend/package.json, frontend/src/components/Activities.vue, frontend/src/components/CallUI.vue, frontend/src/components/ColumnSettings.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/pages/CallLog.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Organization.vue, frontend/src/stores/contacts.js, frontend/src/stores/global.js
=> fix: Call UI fixes

crm/api/doc.py, crm/api/session.py, crm/api/views.py, crm/fcrm/doctype/crm_call_log/crm_call_log.json, crm/fcrm/doctype/crm_communication_status/crm_communication_status.json, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_deal_status/crm_deal_status.json, crm/fcrm/doctype/crm_form_script/crm_form_script.json, crm/fcrm/doctype/crm_holiday_list/crm_holiday_list.json, crm/fcrm/doctype/crm_industry/crm_industry.json, crm/fcrm/doctype/crm_lead/crm_lead.json, crm/fcrm/doctype/crm_lead_source/crm_lead_source.json, crm/fcrm/doctype/crm_lead_status/crm_lead_status.json, crm/fcrm/doctype/crm_note/crm_note.json, crm/fcrm/doctype/crm_organization/crm_organization.json, crm/fcrm/doctype/crm_service_level_agreement/crm_service_level_agreement.json, crm/fcrm/doctype/crm_task/crm_task.json, crm/fcrm/doctype/crm_territory/crm_territory.json, crm/fcrm/doctype/crm_view_settings/crm_view_settings.json, crm/fcrm/doctype/crm_view_settings/crm_view_settings.py, crm/fcrm/doctype/twilio_agents/twilio_agents.json, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/ViewControls.vue, frontend/src/stores/users.js, frontend/src/stores/views.js
https://github.com/frappe/crm/assets/30859809/e6bc73c7-a70c-4b7b-abe0-6a6dd0d5bd9c
=> fix: Public Views

crm/api/doc.py, crm/api/views.py, crm/fcrm/doctype/crm_view_settings/crm_view_settings.json, crm/fcrm/doctype/crm_view_settings/crm_view_settings.py, frontend/src/components/ViewControls.vue, frontend/src/router.js, frontend/src/stores/views.js
https://github.com/frappe/crm/assets/30859809/c07f658f-4337-493b-9869-96a0374fa99c
=> feat: Make Default View

frontend/src/components/CommentBox.vue, frontend/src/components/CommunicationArea.vue, frontend/src/stores/users.js
=> feat: Comment Box

crm/hooks.py, crm/install.py, crm/overrides/email_template.py, crm/uninstall.py, frontend/src/components/CommentBox.vue, frontend/src/components/CommunicationArea.vue, frontend/src/components/EmailEditor.vue, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/Modals/EmailTemplateModal.vue, frontend/src/components/Modals/EmailTemplateSelectorModal.vue, frontend/src/pages/EmailTemplate.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/router.js
https://github.com/frappe/crm/assets/30859809/1dd79d58-5d44-4bde-84e4-90f091252ccd
=> feat: Email Templates

crm/fcrm/doctype/crm_note/crm_note.py, frontend/src/components/Modals/NoteModal.vue, frontend/src/components/Modals/TaskModal.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/Notes.vue, frontend/src/pages/Tasks.vue
=> feat: Added view controls on Notes view

crm/api/doc.py, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/Modals/EditValueModal.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue
=> fix: Bulk Edit from list view

crm/api/doc.py, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue, frontend/src/utils/index.js
=> feat: Custom Bulk Actions

frontend/src/components/Controls/DatetimePicker.vue, frontend/src/components/Filter.vue
=> feat: Added DatetimePicker in filter for datetime fieldtype

frontend/package.json, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/MultipleAvatar.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue
https://github.com/frappe/crm/assets/30859809/a949c2a3-94e1-4cfd-aeb3-40133afee111
=> feat: Apply filter on click if row items in list view

frontend/src/components/ViewControls.vue
https://github.com/frappe/crm/assets/30859809/e67a1be8-c546-49cd-8751-5b9fef4b3a65
=> feat: Export list view data

crm/api/session.py, frontend/src/components/DropdownItem.vue, frontend/src/components/Modals/ContactModal.vue
https://github.com/frappe/crm/assets/30859809/e76c3b79-73b2-497f-9ced-6a197b9a4048
=> feat: Allow CRUD operations for contact email & phone no

crm/api/activities.py, crm/fcrm/doctype/crm_call_log/crm_call_log.json, crm/fcrm/doctype/crm_call_log/crm_call_log.py, crm/fcrm/doctype/fcrm_note/fcrm_note.js, crm/fcrm/doctype/fcrm_note/fcrm_note.json, crm/fcrm/doctype/fcrm_note/fcrm_note.py, crm/fcrm/doctype/fcrm_note/test_fcrm_note.py, crm/twilio/api.py, frontend/src/components/Activities.vue, frontend/src/components/Modals/NoteModal.vue, frontend/src/pages/CallLog.vue, frontend/src/pages/Notes.vue
**CRM Note** doctype already exists in ERPNext. To avoid conflict renamed it to **FCRM Note**
=> fix: Renamed CRM Note to FCRM Note

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .vscode/launch.json, .vscode/settings.json, scripts/init.sh
Quick setup using codespaces.
From [vjFaLk/frappe_codespace](https://github.com/vjFaLk/frappe_codespace)
=> ci: Init Codespaces

crm/api/doc.py, crm/fcrm/doctype/crm_form_script/crm_form_script.js, crm/fcrm/doctype/crm_form_script/crm_form_script.json, crm/fcrm/doctype/crm_form_script/crm_form_script.py, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue, frontend/src/utils/index.js
=> fix: Custom Action in Listview

frontend/index.html
Fixes: https://github.com/frappe/crm/issues/132
=> fix: Only block oversroll vertically

frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue
Before: 
https://github.com/frappe/crm/assets/30859809/80489453-560c-488b-a1ce-21e5492f98ed
After:
https://github.com/frappe/crm/assets/30859809/92761820-08cf-49f1-b72d-42e2c09a4869
=> fix: onlick of text only apply filter

frontend/src/components/ListViews/TasksListView.vue
Fixes: https://github.com/frappe/crm/issues/157
=> fix: Cannot delete task

crm/api/activities.py, crm/api/comment.py, frontend/src/components/Activities.vue, frontend/src/components/CommunicationArea.vue
Fixes: https://github.com/frappe/crm/issues/105
=> feat: Add attachments in comment

frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/UserDropdown.vue
<table>
<tr>
<td>Before</td>
<td>After</td>
<tr>
<td>
</td>
<td>
</td>
</table>
=> fix: added support & docs link in userdropdown menu

frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/stores/statuses.js
Fixes: https://github.com/frappe/crm/issues/161
=> fix: Bug while creating Lead

crm/api/activities.py, frontend/src/components/Activities.vue
PR for #172 
Adding entries from `automated_messages` to `activities` in `crm.api.activities.get_activities` API
=> Email Notifications in Lead/Deal Activity

frontend/src/components/Filter.vue
=> feat: Clear all filter x button

crm/api/doc.py, crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_lead/api.py, frontend/src/components/ListBulkActions.vue, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/Modals/AssignmentModal.vue, frontend/src/components/Modals/EditValueModal.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
fixes: https://github.com/frappe/crm/issues/100
=> feat: Bulk Assign & Clear Assignments

frontend/src/components/Activities.vue, frontend/src/components/CommunicationArea.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
=> feat: Added comment tab

docker/docker-compose.yml, docker/init.sh
Fixes: https://github.com/frappe/crm/issues/178
=> fix: Added docker compose files

crm/api/doc.py, frontend/src/components/CallUI.vue, frontend/src/components/Icons/HeartIcon.vue, frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue
https://github.com/frappe/crm/assets/30859809/750ea202-3b58-484c-9db1-bd60da7c80ff
=> feat: Liked By in List View

frontend/src/components/CustomActions.vue
=> fix: Grouped button with label

crm/api/doc.py, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.js, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.json, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, crm/fcrm/doctype/crm_fields_layout/test_crm_fields_layout.py, crm/install.py, crm/patches.txt, crm/patches/v1_0/create_default_fields_layout.py, frontend/src/components/Fields.vue, frontend/src/components/Modals/ContactModal.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/components/Modals/OrganizationModal.vue
=> feat: Add custom fields in quick entry modal

crm/api/__init__.py, frontend/src/components/Activities.vue, frontend/src/components/CommunicationArea.vue
=> fix: Add email signature from user settings or default email account's signature

crm/api/doc.py, crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.json, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, crm/fcrm/doctype/crm_lead/api.py, crm/patches.txt, crm/patches/v1_0/create_default_sidebar_fields_layout.py, frontend/src/components/Modals/ContactModal.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/components/Resizer.vue, frontend/src/components/SectionFields.vue, frontend/src/components/Settings/FieldsLayout.vue, frontend/src/components/Settings/ProfileSettings.vue, frontend/src/components/Settings/SettingsModal.vue, frontend/src/components/Settings/SettingsPage.vue, frontend/src/components/Settings/SidebarLayoutBuilder.vue, frontend/src/components/Settings/TwilioSettings.vue, frontend/src/components/Settings/WhatsAppSettings.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue
=> feat: Sidebar Fields Layout Builder

frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue
fixes: https://github.com/frappe/crm/issues/224
=> fix: show correct validation error in quick entry modal

crm/install.py
Added a list for industry and lead source just like that for erpnext
=> add: defaults for industry and lead source

crm/fcrm/doctype/crm_lead/crm_lead.py
fixes: https://github.com/frappe/crm/issues/247
=> fix: removed hardcoded values

crm/fcrm/doctype/crm_deal/crm_deal.py
fixes: https://github.com/frappe/crm/issues/248
=> fix: cannot capture custom data from deal modal

frontend/src/components/EmailEditor.vue
fixes: https://github.com/frappe/crm/issues/257
=> feat: emoji picker in email box

frontend/src/pages/Deal.vue
Contacts for the deal was not getting loaded in first load, it gets loaded after refreshing the pages once or twice
=> fix: contacts not loading in deal on first load

crm/fcrm/doctype/crm_lead/crm_lead.py
fixed: https://github.com/frappe/crm/issues/285
=> fix: industry not getting synced on convertion

frontend/src/components/ListBulkActions.vue
fixes: https://github.com/frappe/crm/issues/286
Refactor needed
=> feat: Bulk convert lead

crm/api/doc.py
fixes: https://github.com/frappe/crm/issues/284
=> fix: default list columns doesn't work

frontend/src/pages/EmailTemplates.vue
fixes: https://github.com/frappe/crm/issues/289
=> fix: on creating email template showing old data

frontend/src/components/Modals/AssignmentModal.vue
fixes: https://github.com/frappe/crm/issues/295
=> fix: cannot unassign user

frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/LeadModal.vue
fixes: https://github.com/frappe/crm/issues/296
=> fix: in lead/deal creation modal status is empty

frontend/src/components/ListViews/TasksListView.vue
fixes: https://github.com/frappe/crm/issues/267
=> fix: render description in task list view correctly

frontend/src/components/ViewControls.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Organization.vue
fixes: https://github.com/frappe/crm/issues/291
=> fix: show page meta

crm/fcrm/doctype/crm_view_settings/crm_view_settings.py
fixes: https://github.com/frappe/crm/issues/290
=> fix: pinned view should become unpinned when made public

crm/api/__init__.py, frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/WhatsAppArea.vue, frontend/src/components/Activities/WhatsAppBox.vue, frontend/src/components/Apps.vue, frontend/src/components/CallUI.vue, frontend/src/components/CommentBox.vue, frontend/src/components/CommunicationArea.vue, frontend/src/components/EmailEditor.vue, frontend/src/components/ListBulkActions.vue, frontend/src/components/Modals/AssignmentModal.vue, frontend/src/components/Modals/ContactModal.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/EditValueModal.vue, frontend/src/components/Modals/EmailTemplateModal.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/components/Modals/NoteModal.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/components/Modals/TaskModal.vue, frontend/src/components/Modals/WhatsappTemplateSelectorModal.vue, frontend/src/components/Notifications.vue, frontend/src/components/SLASection.vue, frontend/src/components/Settings/QuickEntryModal.vue, frontend/src/components/Settings/SidePanelModal.vue, frontend/src/main.js, frontend/src/pages/Lead.vue, frontend/src/stores/statuses.js, frontend/src/telemetry.ts
fixes: https://github.com/frappe/crm/issues/315
=> feat: Init posthog telemetry to analyse crm usage

crm/api/__init__.py, crm/fcrm/doctype/crm_invitation/crm_invitation.js, crm/fcrm/doctype/crm_invitation/crm_invitation.json, crm/fcrm/doctype/crm_invitation/crm_invitation.py, crm/fcrm/doctype/crm_invitation/test_crm_invitation.py, crm/templates/emails/crm_invitation.html, frontend/src/components/Controls/MultiValueInput.vue, frontend/src/components/Settings/InviteMemberPage.vue, frontend/src/components/Settings/SettingsModal.vue, frontend/src/components/SidebarLink.vue, frontend/src/utils/index.js
=> feat: Invite Members

frontend/src/components/Activities/EmailArea.vue, frontend/src/components/Settings/InviteMemberPage.vue, frontend/src/pages/Deal.vue
fixes: https://github.com/frappe/crm/issues/271
fixes: https://github.com/frappe/crm/issues/326
=> fix: UI/UX improvements & minor bug fixes

crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_lead/crm_lead.json, crm/fcrm/doctype/crm_organization/crm_organization.json, crm/fcrm/doctype/erpnext_crm_settings/erpnext_crm_settings.js, crm/fcrm/doctype/erpnext_crm_settings/erpnext_crm_settings.py, frontend/src/pages/Deals.vue, frontend/src/pages/Leads.vue, frontend/src/pages/Organizations.vue, frontend/src/utils/index.js
<kbd>
</kbd>
<kbd>
</kbd>
fixes: https://github.com/frappe/crm/issues/343
=> fix: View Customer & Reset ERPNext Form Script

frontend/src/components/ListViews/TasksListView.vue
Calendar icon of Datetime field in task listview was not rendered properly.
This PR fixes it<br><br>
**Before**
**After**
=> fix(ui): Calendar icon in task listview

crm/api/comment.py, crm/api/todo.py, crm/api/whatsapp.py, crm/fcrm/doctype/crm_notification/crm_notification.json, crm/fcrm/doctype/crm_notification/crm_notification.py, crm/fcrm/doctype/crm_task/crm_task.py, crm/hooks.py
fixes: https://github.com/frappe/crm/issues/104
=> fix: More Notifications

crm/api/activities.py, frontend/src/components/Activities/EmailArea.vue
=> fix: show email status read/sent on UI

frontend/src/components/Modals/EmailTemplateModal.vue
1. Email template not saving if `use_html` is set
2. Added content type select instead of `use_html` checkbox
=> fix: Added content type instead of use html checkbox

crm/api/__init__.py, crm/api/activities.py, crm/www/crm.py, frontend/package.json, frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/ActivityHeader.vue, frontend/src/components/Activities/AttachmentArea.vue, frontend/src/components/Activities/TaskArea.vue, frontend/src/components/FilesUploader/FilesUploader.vue, frontend/src/components/FilesUploader/FilesUploaderArea.vue, frontend/src/components/FilesUploader/filesUploaderHandler.ts, frontend/src/components/Icons/FileAudioIcon.vue, frontend/src/components/Icons/FileVideoIcon.vue, frontend/src/components/Settings/SettingsPage.vue, frontend/src/composables/useActiveTabManager.js, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/stores/statuses.js, frontend/src/utils/index.js
> Upload by browsing files (Library) - Will add in separate PR
**Web Link**
**Camera**
**Attachments Tab**
**Attachments in activity**
fixes: https://github.com/frappe/crm/issues/102
=> feat: file uploader

frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/TaskArea.vue, frontend/src/components/FilesUploader/FilesUploader.vue, frontend/src/components/FilesUploader/FilesUploaderArea.vue
=> fix: file uploader fixes

frontend/src/components/Modals/ContactModal.vue
fixes: https://github.com/frappe/crm/issues/421
=> fix: cannot update email in contact

frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/Mobile/MobileSidebar.vue, frontend/src/components/Notifications.vue, frontend/src/pages/MobileNotification.vue, frontend/src/stores/notifications.js
=> refactor: notifications panel code

frontend/src/components/Activities/WhatsAppArea.vue
@shariquerik 
`frappe_whatsapp` recently added support for accepting incoming messages using quick reply buttons in [this](https://github.com/shridarpatil/frappe_whatsapp/pull/102) PR.
This just extends that feature to the CRM.
=> feat: add support for incoming messages using quick reply buttons

crm/www/crm.py, frontend/package.json, frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/AttachmentArea.vue, frontend/src/components/Activities/CallArea.vue, frontend/src/components/Activities/CommentArea.vue, frontend/src/components/Activities/EmailArea.vue, frontend/src/components/Activities/NoteArea.vue, frontend/src/components/Activities/TaskArea.vue, frontend/src/components/Activities/WhatsAppArea.vue, frontend/src/components/FilesUploader/FilesUploaderArea.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/components/SLASection.vue, frontend/src/components/SectionFields.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deals.vue, frontend/src/pages/EmailTemplates.vue, frontend/src/pages/Leads.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Notes.vue, frontend/src/pages/Organization.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Tasks.vue, frontend/src/utils/callLog.js, frontend/src/utils/index.js
Dependent on https://github.com/frappe/frappe-ui/pull/229
=> fix: Timezone support in Date & DateTime fields

frontend/package.json, frontend/src/App.vue, frontend/src/components/Activities/CallArea.vue, frontend/src/components/Activities/TaskArea.vue, frontend/src/components/Activities/WhatsAppArea.vue, frontend/src/components/FilesUploader/FilesUploaderArea.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/pages/Tasks.vue, frontend/src/utils/index.js
dependent on: https://github.com/frappe/frappe-ui/pull/234
=> fix: Replaced luxon with dayjs

yarn.lock
=> chore: Regenerate yarn.lock (develop)

frontend/src/components/ListViews/CallLogsListView.vue, frontend/src/components/ListViews/ContactsListView.vue, frontend/src/components/ListViews/DealsListView.vue, frontend/src/components/ListViews/EmailTemplatesListView.vue, frontend/src/components/ListViews/LeadsListView.vue, frontend/src/components/ListViews/ListRows.vue, frontend/src/components/ListViews/OrganizationsListView.vue, frontend/src/components/ListViews/TasksListView.vue, frontend/src/router.js
When you open any record from listview and again come back to listview it scrolls to that record. The scroll animation is not needed so implemented the same without scroll animation but took a better approach
=> fix: remove the scroll behaviour in listview

crm/fcrm/doctype/fcrm_settings/fcrm_settings.json, frontend/src/components/BrandLogo.vue, frontend/src/components/UserDropdown.vue, frontend/src/components/ViewControls.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue, frontend/src/stores/settings.js
Add Custom Brand Logo, Name & favicon
FCRM Settings - Branding tab
=> feat: Custom Branding

.github/workflows/builds.yml
Easy install commands do not work as per README.
=> fix: stable tag for docker image

crm/fcrm/doctype/crm_call_log/crm_call_log.json, crm/fcrm/doctype/crm_call_log/crm_call_log.py, crm/install.py, crm/integrations/api.py, crm/patches.txt, crm/patches/v1_0/create_default_fields_layout.py, frontend/src/components/Activities/CallArea.vue, frontend/src/components/Modals/CallLogDetailModal.vue, frontend/src/components/Modals/CallLogModal.vue, frontend/src/components/Modals/TaskModal.vue, frontend/src/pages/CallLogs.vue, frontend/src/utils/callLog.js
fixes: https://github.com/frappe/crm/issues/121
Create
Edit
Add/Edit Note & Task
Note & Task in Call Details
=> feat: Manually create and update existing call log

frontend/src/components/Settings/ProfileSettings.vue
=> fix: update password from profile settings

crm/api/doc.py
fixes: https://github.com/frappe/crm/issues/570
=> fix: hide column from listview if field is hidden

frontend/src/components/SidePanelLayout.vue, frontend/src/pages/Deal.vue, frontend/src/pages/MobileDeal.vue
fixes: https://github.com/frappe/crm/issues/552
=> fix: cannot add/create contact from deal

frontend/src/pages/Deal.vue, frontend/src/pages/MobileDeal.vue
fixes: https://github.com/frappe/crm/issues/554
=> fix: same contact can be added multiple time

crm/api/doc.py, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.json, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, crm/fcrm/doctype/crm_lead/crm_lead.py, frontend/package.json, frontend/src/components/FieldLayoutEditor.vue, frontend/src/components/Modals/QuickEntryModal.vue, frontend/src/components/SignupBanner.vue, frontend/src/pages/Lead.vue, yarn.lock
=> feat: Show required fields while converting to deal

frontend/src/components/Controls/Link.vue
fixes: https://github.com/frappe/crm/issues/355
=> fix: show title and description in link field

frontend/src/components/Controls/Link.vue, frontend/src/components/Controls/MultiValueInput.vue, frontend/src/components/Controls/TableMultiselectInput.vue, frontend/src/components/FieldLayout/Field.vue, frontend/src/components/SidePanelLayoutEditor.vue
=> feat: Table Multi Select Control

crm/api/doc.py, crm/fcrm/doctype/crm_global_settings/crm_global_settings.js, crm/fcrm/doctype/crm_global_settings/crm_global_settings.json, crm/fcrm/doctype/crm_global_settings/crm_global_settings.py, crm/fcrm/doctype/crm_global_settings/test_crm_global_settings.py, frontend/src/components/Icons/ExportIcon.vue, frontend/src/components/Icons/QuickFilterIcon.vue, frontend/src/components/ViewControls.vue
<kbd>
</kbd>
Add new filters, remove or rearrange existing filters by dragging
<kbd>
</kbd>
=> feat: Customize Quick Filters

crm/fcrm/doctype/crm_service_level_agreement/crm_service_level_agreement.py
Unable to edit the default SLA
=> fix: ignore current document in default SLA validation

.github/helper/update_pot_file.sh, .github/workflows/ci.yml, .github/workflows/generate-pot-file.yml, crm/crowdin.yml, crm/locale/es.po
Auto generate pot file
Original Frappe PR for reference: https://github.com/frappe/frappe/pull/24467
=> ci: auto-generate pot file

frontend/src/components/Controls/MultiValueInput.vue, frontend/src/components/Settings/InviteMemberPage.vue
=> fix(UX): added description to which says press enter to add email

frontend/src/pages/Contact.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue
=> fix: show title value if exist in breadcrumbs or name

frontend/src/components/Activities/AttachmentArea.vue, frontend/src/components/Activities/TaskArea.vue, frontend/src/components/Modals/AssignmentModal.vue, frontend/src/components/Settings/InviteMemberPage.vue, frontend/src/components/ViewBreadcrumbs.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
This is causing double call log entry because make call was getting triggered twice
=> fix: button inside tooltip is triggered twice

crm/fcrm/doctype/crm_call_log/crm_call_log.json, crm/fcrm/doctype/fcrm_note/fcrm_note.json, frontend/src/components/Modals/CallLogModal.vue, frontend/src/components/Modals/NoteModal.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/components/Modals/TaskModal.vue
Made fields mandatory and handled validation errors to display error messages.
Fixes #680
=> fix: add mandatory fields

crm/api/doc.py
=> fix: kanban filter

frontend/src/components/Controls/Grid.vue, frontend/src/components/Controls/Link.vue, frontend/src/components/FieldLayout/Field.vue, frontend/src/components/SidePanelLayout.vue
=> feat: Dynamic Link field support

frontend/components.d.ts, frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/ActivityHeader.vue, frontend/src/components/Activities/AllModals.vue, frontend/src/components/MultiActionButton.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
=> fix: Create & Make call

frontend/src/components/Activities/DataFields.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue
Steps to reproduce
1. Go to Data tab
2. Then switch to some other tab e.g. Notes tab
3. Then again switch back to Data tab
4. Change any field
5. Save button will stay disabled, form is not getting dirty.
=> fix: mark data tab form dirty by watching field updates

crm/api/contact.py, frontend/src/pages/Contact.vue, frontend/src/pages/Organization.vue
Getting error even if has access
=> fix: contact page not loading

frontend/src/components/Settings/EmailAccountCard.vue, frontend/src/components/Settings/EmailAccountList.vue, frontend/src/components/Settings/EmailAdd.vue, frontend/src/components/Settings/EmailEdit.vue, frontend/src/components/Settings/emailConfig.js
add localization support for email account settings
=> chore: add localization support for email account settings

crm/integrations/api.py
Fixed bug where when international calls are made the the receiver was not getting linked to call logs
=> fix: international call log issue

crm/templates/emails/crm_invitation.html, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/pages/Lead.vue
1. Gray out dependent steps based on "dependsOn" property.
2. Get filtered steps based on condition set
3. Store firstLead & firstDeal per user in local storage
=> fix: Onboarding fixes

crm/api/__init__.py, crm/fcrm/doctype/crm_form_script/crm_form_script.json, crm/fcrm/doctype/crm_invitation/crm_invitation.py, frontend/components.d.ts, frontend/src/components/Controls/Grid.vue, frontend/src/components/Controls/MultiSelectEmailInput.vue, frontend/src/components/Controls/Password.vue, frontend/src/components/FieldLayout/Field.vue, frontend/src/components/Icons/SquareAsterisk.vue, frontend/src/components/Layouts/AppSidebar.vue, frontend/src/components/Settings/InviteMemberPage.vue, frontend/src/components/Settings/ProfileSettings.vue, frontend/src/components/SidePanelLayout.vue
1. Only set "FCRM" module if role set is "Sales User"
2. Do not show existing contacts in dropdown in "Invite Member Page"
3. Added Password Control
4. Added "Setup your password" step in onboarding
=> fix: Invite Member Page

crm/fcrm/doctype/fcrm_settings/fcrm_settings.py, crm/hooks.py, crm/www/crm.py, frontend/components.d.ts, frontend/src/components/Icons/TelegramIcon.vue, frontend/src/components/Modals/AboutModal.vue, frontend/src/components/Modals/GlobalModals.vue, frontend/src/components/UserDropdown.vue, frontend/src/composables/settings.js
=> feat: About Modal

frontend/src/components/Filter.vue, frontend/src/components/ViewControls.vue
Hide selected filters from the filter list
Closes #677
=> fix: hide selected filters from filter list

frontend/src/components/Controls/TableMultiselectInput.vue
fixes: https://github.com/frappe/crm/issues/851
=> fix: set default value as empty array

crm/fcrm/doctype/crm_call_log/crm_call_log.py, frontend/src/components/FieldLayout/Field.vue, frontend/src/components/Modals/CallLogDetailModal.vue, frontend/src/data/document.js
fixes: https://github.com/frappe/crm/issues/855
=> feat: intercept create lead from call log via form script

frontend/src/data/document.js, frontend/src/pages/Lead.vue
=> feat: intercept convert to deal via form script

frontend/src/components/ViewControls.vue
Fix a bug when exporting data with an employee filter is applied
Closes #338
=> fix: export with filter

frontend/src/telemetry.ts
fix this for reenabling: https://github.com/frappe/crm/issues/883
=> fix: remove invasive settings

frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/AllModals.vue, frontend/src/components/Activities/CallArea.vue, frontend/src/components/Layouts/MobileLayout.vue, frontend/src/components/Modals/AddressModal.vue, frontend/src/components/Modals/CallLogModal.vue, frontend/src/components/Modals/ContactModal.vue, frontend/src/components/Modals/CreateDocumentModal.vue, frontend/src/components/Modals/DealModal.vue, frontend/src/components/Modals/GlobalModals.vue, frontend/src/components/Modals/LeadModal.vue, frontend/src/components/Modals/OrganizationModal.vue, frontend/src/components/UserDropdown.vue, frontend/src/composables/modals.js, frontend/src/composables/settings.js, frontend/src/data/document.js, frontend/src/data/script.js, frontend/src/pages/CallLogs.vue, frontend/src/pages/Contact.vue, frontend/src/pages/Contacts.vue, frontend/src/pages/Deal.vue, frontend/src/pages/Deals.vue, frontend/src/pages/Lead.vue, frontend/src/pages/Leads.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue, frontend/src/pages/Organizations.vue, frontend/src/pages/Welcome.vue
1. Class based form script was not applied on New Modal (Lead/Deal/Contact/Organization/Address)
2. Moved all common modal in GlobalModal which can be triggered from anywhere
=> fix: Apply Class Based Form Script in New Modal

frontend/src/data/document.js, frontend/src/data/script.js, frontend/src/pages/Deal.vue, frontend/src/pages/Lead.vue, frontend/src/pages/MobileDeal.vue, frontend/src/pages/MobileLead.vue
<kbd>
</kbd>
https://github.com/user-attachments/assets/24373a60-ccc3-4558-a998-b48be6119b57
=> feat: Custom actions/statuses via Class Based Script

frontend/src/components/Settings/Settings.vue
=> fix: add context for Integrations

crm/fcrm/doctype/crm_deal/crm_deal.py, crm/fcrm/doctype/crm_deal_status/crm_deal_status.json, crm/fcrm/doctype/crm_fields_layout/crm_fields_layout.py, crm/fcrm/doctype/fcrm_settings/fcrm_settings.json, crm/fcrm/doctype/fcrm_settings/fcrm_settings.py, crm/install.py, crm/patches.txt, crm/patches/v1_0/update_deal_status_probabilities.py, frontend/components.d.ts, frontend/src/components/Modals/AddressModal.vue, frontend/src/components/Modals/CallLogModal.vue, frontend/src/components/Modals/ConvertToDealModal.vue, frontend/src/data/document.js, frontend/src/pages/Lead.vue, frontend/src/utils/index.js
fixes: https://github.com/frappe/crm/issues/969
1. Qualification -10%
2. Demo/Making - 25%
3. Proposal / Quotation - 50%
4. Negotiation - 70%
5. Ready to close - 90%
6. Won - 100%
7. Lost - 0%
<kbd><img width="1003" alt="Screenshot 2025-07-01 at 4 10 08 PM" src="https://github.com/user-attachments/assets/45c02540-b08e-4820-a6cf-595ae8a24125" /></kbd>
<kbd><img width="519" alt="Screenshot 2025-07-01 at 4 11 04 PM" src="https://github.com/user-attachments/assets/84637d36-1cda-4c17-9819-475ff383fb50" /></kbd>
<kbd><img width="1142" alt="Screenshot 2025-07-01 at 4 12 05 PM" src="https://github.com/user-attachments/assets/5a4a5bbb-b0ad-4539-b402-2de40da42221" /></kbd>
<kbd><img width="1436" alt="Screenshot 2025-07-01 at 4 37 17 PM" src="https://github.com/user-attachments/assets/21299bb3-e737-4 …
=> fix: Forecasting fixes

frontend/src/utils/index.js
Before:
<kbd><img width="826" alt="Screenshot 2025-07-01 at 7 21 16 PM" src="https://github.com/user-attachments/assets/af0bf7e6-b14b-4d5b-81af-a04ee4dad862" /></kbd>
After:
<kbd><img width="826" alt="Screenshot 2025-07-01 at 7 20 51 PM" src="https://github.com/user-attachments/assets/e813d95e-3c56-4e71-b963-3d262fd214dc" /></kbd>
=> fix: show absolute day count not in decimals

frontend/src/data/document.js
fixes: https://github.com/frappe/crm/issues/1000
=> fix: grid field is not getting set

crm/api/contact.py, crm/fcrm/doctype/crm_deal/api.py, crm/fcrm/doctype/crm_deal/crm_deal.json, crm/fcrm/doctype/crm_lead/api.py, frontend/src/components/SidePanelLayout.vue, frontend/src/pages/Contact.vue, frontend/src/pages/MobileContact.vue, frontend/src/pages/MobileOrganization.vue, frontend/src/pages/Organization.vue
fixes: https://github.com/frappe/crm/issues/807
=> refactor: Contact & Organization page

frontend/src/components/Modals/EditValueModal.vue
use fieldname instead of .value => its undefined
error :
solution :
=> fix: set fieldname to handle bulk edit value modal

crm/api/dashboard.py, crm/integrations/exotel/handler.py, frontend/src/pages/Dashboard.vue
=> fix: Reset to default dashboard

crm/fcrm/doctype/crm_deal/crm_deal.py, crm/utils/__init__.py, frontend/src/data/document.js
Also,
Fixes: https://github.com/frappe/crm/issues/1044
Fixes: https://github.com/frappe/crm/issues/1047
=> refactor: Assignees logic

frontend/src/components/Modals/ContactModal.vue
Fixes: https://github.com/frappe/crm/issues/936
=> fix: make mobile no primary on create of contact

frontend/src/components/Activities/Activities.vue, frontend/src/components/Activities/ActivityHeader.vue, frontend/src/components/MultiActionButton.vue
Before:
<kbd><img width="852" height="329" alt="Screenshot 2025-07-24 at 1 13 03 PM" src="https://github.com/user-attachments/assets/bae1a281-3dad-4c09-bd4f-836132459ccf" />
After:
<kbd><img width="851" height="321" alt="Screenshot 2025-07-24 at 1 12 22 PM" src="https://github.com/user-attachments/assets/f443152a-7a33-45f1-865e-ebe28b9d9e28" />
Fixes: https://github.com/frappe/crm/issues/730
=> refactor: Call Log Button

frontend/src/components/Settings/AssignmentRules/AssigneeRules.vue, frontend/src/components/Settings/AssignmentRules/AssignmentRuleView.vue, frontend/src/components/Settings/AssignmentRules/AssignmentRules.vue, frontend/src/components/Settings/EmailTemplate/EditEmailTemplate.vue, frontend/src/components/Settings/EmailTemplate/NewEmailTemplate.vue, frontend/src/components/Settings/General/BrandSettings.vue, frontend/src/components/Settings/General/CurrencySettings.vue, frontend/src/components/Settings/General/HomeActions.vue, yarn.lock
Fix paddings and labels for the assignment rule
=> fix: paddings and labels

frontend/src/data/document.js, frontend/src/utils/index.js
Before this fix when you update fields in Deal or Lead without setting mandatory field it get saved without erroring out.
dependent on: https://github.com/frappe/frappe-ui/pull/409 & frappe-ui [v0.1.201](https://github.com/frappe/frappe-ui/releases/tag/v0.1.201)
=> fix: add validation for mandatory fields in useDocument
